name: jlfastcred_core
description: "A new Flutter package project."
version: 0.0.1
homepage:

environment:
  sdk: '>=3.2.5 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^4.5.3
  firebase_auth: ^4.4.2
  firebase_storage: ^11.2.2
  signals_flutter: ^3.0.0 #gerencia de estado
  top_snackbar_flutter: ^3.1.0
  flutter_getit: ^2.0.0
  asyncstate: ^2.1.1-dev.1
  loading_animation_widget: ^1.2.0+4
  json_annotation: ^4.8.1 
  brasil_fields: ^1.14.2 #formatadores para os campos do Brasil
  validatorless: ^1.2.3 #validação de formulários
  shared_preferences: ^2.2.2 #salvar dados
  file_picker: ^8.0.0+1
  dio: ^5.4.0
  pretty_dio_logger: ^1.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  json_serializable: ^6.7.1 #convert json automatico
  build_runner: ^2.4.8 #gerador de código

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
